### PR TITLE
Active record additions

### PR DESCRIPTION
**Pull request by universal**
Adds basic support for:
  * attachments
  * (global)equivalent domains -- even though with the multiple uri per cipher support now, this is not so important anymore
  * webvault

Implemented ontop of the active-record branch, this adds support for file attachments, equivalent domains and webvault compatibility.  Attachments are stored in data/attachments. 

(Global)EquivalentDomains have dedicated tables and interacting with them through the web-vault works.  A tool to generate an initial list of GlobalEquivalentDomains has been added. With the addition of active-record it probably makes more sense to move this to a database seeds file.

To compile the webvault a simple scripts has been added under ```tools/compile_webvault.rb```. it checks out the code from github using a tagged release to ```tmp/web```. It then performs the config changes necessary for a self-hosted installation and puts the compiled webvault into the ```public``` folder. The public folder is served by sinatra, though if you use something like nginx in front, you probably want to set the document_root to ```APP_ROOT/public```.

### CODE REVIEW

**Comment by Pschittt** [comment]
Hello,

I've tested your branch, and was facing multiple problems : 
- If a database file is not already present, your branch doesn't create a new one.
- The attachments feature doesn't seem to be available.

**Comment by universal** [comment]
Hi,

thanks alot for testing the code!

### database file:

This is something I left as an open question in the base pull request for switching to active-record. If we want to keep the current mechanism of running migrations automatically on load or have it as a separate step  by invoking ```rake db:migrate```. This needs some more documentation.

### attachments

Hmm... I'm not sure if you've to manually set the premium flag on the in the user: ```irb; require_relative 'lib/bit...; User.update_all premium: true```

This mostly works for me, but the attachment feature is somewhat hidden in the web-vault to start with: It is hidden behind the settings wheel to the left of an entry. I just tested adding an attachment and downloading it. I noticed that the response contains the json content-type headers. This is something I've to check and also set data-disposition or alike, so the browser knows it should save the file. 

### Import Tool

Which import tool? The migrate_to_ar.rb tool? This worked for my database, but if you have a test database showing problems I would love to take a look. If you could send it to me I'd be grateful :-)

**Comment by Pschittt** [comment]
**Attachments**
Indeed, the feature is hidden. Tested and it works.

**Import**
I've used the import function via the web vault. I tought it was implemented, seems to be partially implemented.

**Comment by thomasave** [comment]
Thanks for adding support for attachments! It's a lot more elegant than my current solution (storing the base64 of the file as a note).
However, I'm having trouble running the migration to ActiveRecord with a database created by the current master:
```
Traceback (most recent call last):
        26: from tools/migrate_to_ar.rb:50:in `<main>'
        25: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/yaml_db-0.6.0/lib/yaml_db/serialization_helper.rb:17:in `dump'
        24: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/yaml_db-0.6.0/lib/yaml_db/serialization_helper.rb:17:in `open'
        23: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/yaml_db-0.6.0/lib/yaml_db/serialization_helper.rb:18:in `block in dump'
        22: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/yaml_db-0.6.0/lib/yaml_db/serialization_helper.rb:156:in `dump'
        21: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/yaml_db-0.6.0/lib/yaml_db/serialization_helper.rb:156:in `each'
        20: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/yaml_db-0.6.0/lib/yaml_db/serialization_helper.rb:158:in `block in dump'
        19: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/yaml_db-0.6.0/lib/yaml_db/serialization_helper.rb:172:in `dump_table'
        18: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/yaml_db-0.6.0/lib/yaml_db/serialization_helper.rb:199:in `table_record_count'
        17: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:49:in `select_one'
        16: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:97:in `select_all'
        15: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:42:in `select_all'
        14: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:371:in `select'
        13: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/sqlite3_adapter.rb:208:in `exec_query'
        12: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'
        11: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
        10: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block in log'
         9: from /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
         8: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:613:in `block (2 levels) in log'
         7: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/sqlite3_adapter.rb:209:in `block in exec_query'
         6: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
         5: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
         4: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
         3: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/sqlite3_adapter.rb:212:in `block (2 levels) in exec_query'
         2: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `prepare'
         1: from bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `new'
bitwarden-ruby/vendor/bundle/ruby/2.5.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `initialize': SQLite3::SQLException: no such table: equivalent_domains: SELECT COUNT(*) FROM "equivalent_domains" (ActiveRecord::StatementInvalid)
```
I wish there was an export tool, then I could just use one of the existing import tools without having to deal with database migrations.

**Comment by mprasil** [comment]
Hey @thomasave I used the export functionality in Vault to move my data from this Ruby based solution to the [Rust implementation](https://hub.docker.com/r/mprasil/bitwarden/). Perhaps you could use that if the import works in the Ruby version and if you're willing to move data one person at a time. 

Also be aware that the export only exports passwords, doesn't seem to export notes or credit cards. You also won't be able to move shared (organization) passwords this way, but I think this Ruby version doesn't have support for that yet (?) so most likely not an issue.

**Comment by universal** [comment]
@thomasave I see where the problem is. I hope I can push some code to fix this today, but something like the following should solve this:

```ruby
class YamlDb::SerializationHelper::Dump
  def self.tables
    db_tables = ActiveRecord::Base.connection.tables.reject { |table| ['schema_info', 'schema_migrations', 'schema_version'].include?(table) }.sort
    model_tables = ObjectSpace.each_object(Class).select {|k| k < DBModel}.map {|k| k.table_name }
    db_tables & model_tables
  end
end

```

**Comment by jcs** [comment]
@universal I'm not sure what of this is still relevant but if anything after the AR merge is still needed, please create a new PR for it so I can look at it.  Thanks.

**Comment by universal** [comment]
@jcs I hope I find some time soonish to update this pull-request and I will submit it as a new one then. I'll try to integrate the additional features from this pull requests as separate ones.

Just to summarize again for me as well: Attachments, web-vault and (Global)EquivalentDomains

**Pull request closed without merging**
