### PR TITLE
Add Chrome import tool

### PR DESCRIPTION
**Pull request by halukunal**
I created an import tool for Chrome passwords from bitwarden_import.rb

- Chrome exports passwords as CSV file.
- File has 4 fields: name, url, username, password
- Fields are unencrypted.
- No folders/groups.

I tested with 2 accounts and it works.

### CODE REVIEW

**Comment by jcs** [comment]
I would like to have test files that can be used with each importer.  Can you also include a sample CSV file from Chrome?

https://github.com/jcs/rubywarden/issues/67

**Comment by halukunal** [comment]
Here is the sample csv export from Chrome. Github attachment don't support csv extension.

[Chrome Passwords.txt](https://github.com/jcs/rubywarden/files/4847025/Chrome.Passwords.txt)

**Comment by jcs** [comment]
I mean add it to your merge request as a file in `spec/fixtures/`

**Comment by halukunal** [comment]
Sample Chrome Passwords export file uploaded to spec/fixtures/ folder.

**Pull request merged**
